### ISSUE TITLE
User Story - Photoshop File - Login/User Issue

### ISSUE THREAD

**Issue by djphan** [CMPUT301F14T02/Agora#1]
Update the login section as specified on the fourms: " You can[Treat Each Device as a Seperate User]. I'm not asking for the app to be multiuser. But the system is. "

**Comment by sobolews** [comment]
I guess this pretty much invalidates Textual Use Case 1 (SetUsername)?

**Comment by heykevin** [comment]
Shouldn't you still be able to set a username for authorship and whatnot?

**Comment by sobolews** [comment]
I thought we had discussed that the user would set their username once (at first launch of the app on their phone), and then that would become permanent for that installation of the app. That way we have device=user and we don't have a multiuser app (but the system is multiuser because different installations of the app on different phones access the same database)

So I suppose that wouldn't invalidate the use case, but it'll change it... the goal shouldn't be to "change" the username, just to set it the one time?
I'll go ahead and edit the use case, and if we decide we don't like it that way then we'll have to revisit how the usernames work?

**Comment by sobolews** [comment]
Should we allow for the user not to set their username on first launch of the app?
If we insist that they set a username right away, then we don't even have to deal with issues of trying to author without being signed in, differences between "user" and "author", etc..

**Comment by heykevin** [comment]
Ahh okay, I sorta remember that. That sounds good to me.

And yeah they should just set their username on the first launch, seems easier. That means I should edit the use cases in which they aren't signed in.

**Comment by sobolews** [comment]
I'm just finished touching up the UML, when I send it to Dr Hindle I'll ask him if we can insist that the user sets their username on first launch.

**Comment by jaeyoon1** [comment]
so should i remove all the set username button on the storyboard?

and will the initial username settings on launch be a popup on the questionview or a entire view of its own?

**Comment by sobolews** [comment]
Yes.
I would think just a popup on the first launch of the app, overtop of the questionview.

**Comment by jaeyoon1** [comment]
Storyboard is somewhat complete and uploaded
https://github.com/CMPUT301F14T02/TheBrogrammers/blob/master/Storyboard.png

Feel free to check over for issues and close this issue if there are none.
