### ISSUE TITLE
Use Case: As a sysadmin, I do not want the pictures to be large (> 64kb).

### ISSUE THREAD

**Issue by heykevin** [CMPUT301F14T02/Agora#12]

**Comment by djphan** [comment]
Have we decided how to handle this as a use case (if it is one?). Since we are going the route to resize he image to be <= 64kb in our app its more handled on the program side. Or would the flow be like: 1. Follow standard upload image file use case. 2. System resizes images, etc, etc. or would the size shift fall under the exceptions for uploading images

**Comment by sobolews** [comment]
Writing JUnit test
